/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import database.ConnectionProvider;

/**
 *
 * @author Solanid
 */
public class ChangePasswordForm extends javax.swing.JDialog {
    private int idemp;
    
    /**
     * Creates new form ChangePasswordForm
     */
    public ChangePasswordForm(java.awt.Frame parent, boolean modal, int idemp) {
        super(parent, modal);
        initComponents();
        lblErrorBadPassword.setVisible(false);
        lblErrorDoNotMatch.setVisible(false);
        lblInvalidPassword.setVisible(false);
        this.idemp=idemp;
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtOldPassword = new javax.swing.JLabel();
        txtNewPasword1 = new javax.swing.JLabel();
        txtNewPassword2 = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        txtOldPass = new javax.swing.JPasswordField();
        txtNewPass1 = new javax.swing.JPasswordField();
        txtNewPass2 = new javax.swing.JPasswordField();
        lblErrorDoNotMatch = new javax.swing.JLabel();
        lblErrorBadPassword = new javax.swing.JLabel();
        lblInvalidPassword = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtOldPassword.setText("Current password:");

        txtNewPasword1.setText("New password:");

        txtNewPassword2.setText("Confirm new password:");

        btnConfirm.setText("Confirm");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        txtNewPass2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewPass2ActionPerformed(evt);
            }
        });

        lblErrorDoNotMatch.setForeground(new java.awt.Color(255, 51, 51));
        lblErrorDoNotMatch.setText("Passwords do not match !");

        lblErrorBadPassword.setForeground(new java.awt.Color(255, 51, 51));
        lblErrorBadPassword.setText("Incorrect password !");

        lblInvalidPassword.setForeground(new java.awt.Color(255, 51, 51));
        lblInvalidPassword.setText("Invalid password !");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNewPasword1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNewPassword2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOldPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblErrorDoNotMatch)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtNewPass2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblInvalidPassword)
                        .addComponent(txtNewPass1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblErrorBadPassword)
                        .addComponent(txtOldPass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOldPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorBadPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNewPass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNewPasword1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInvalidPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNewPass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNewPassword2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorDoNotMatch, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnConfirm))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
       String oldPassword = new String(txtOldPass.getPassword());
       String newPassword1 = new String(txtNewPass1.getPassword());
       String newPassword2 = new String(txtNewPass2.getPassword());
       
       boolean validPassword = isPasswordValid(newPassword1);
       boolean samePasswords = newPassword1.equals(newPassword2);
       lblInvalidPassword.setVisible(false);
        if (!validPassword) {
            if (newPassword1.trim().length()==0) {
                lblInvalidPassword.setText("Enter new password !");
                lblInvalidPassword.setVisible(true);
            } else {
                lblInvalidPassword.setText("Invalid password !");
                lblInvalidPassword.setVisible(true);                    
            }
        }
        if (samePasswords) {
            lblErrorDoNotMatch.setVisible(false);
        } else {
            lblErrorDoNotMatch.setVisible(true);
        }
        boolean correctOldPassword = new ConnectionProvider().isEmployeePasswordValid(idemp, oldPassword);
        System.out.println(correctOldPassword);
        if (correctOldPassword) {
            lblErrorBadPassword.setVisible(false);
        } else {
            lblErrorBadPassword.setVisible(true);
        }
        if (samePasswords && correctOldPassword && validPassword) {
            ConnectionProvider conn = new ConnectionProvider();
            conn.changePassword(idemp, newPassword1);
            this.dispose();
        }
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtNewPass2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewPass2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewPass2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JLabel lblErrorBadPassword;
    private javax.swing.JLabel lblErrorDoNotMatch;
    private javax.swing.JLabel lblInvalidPassword;
    private javax.swing.JPasswordField txtNewPass1;
    private javax.swing.JPasswordField txtNewPass2;
    private javax.swing.JLabel txtNewPassword2;
    private javax.swing.JLabel txtNewPasword1;
    private javax.swing.JPasswordField txtOldPass;
    private javax.swing.JLabel txtOldPassword;
    // End of variables declaration//GEN-END:variables
    
    private boolean isPasswordValid(String newPassword) {
        newPassword = newPassword.trim();
        if (newPassword.length()<6) {
            return false;
        }
        boolean lowLetter = false;
        boolean uppLetter = false;
        boolean digit = false;
        boolean nonAlphaNum = false;
        for (int i = 0; i < newPassword.length(); i++) {
            if (Character.isLowerCase(newPassword.charAt(i)))
                lowLetter = true;
            if (Character.isUpperCase(newPassword.charAt(i)))
                uppLetter = true;
            if (Character.isDigit(newPassword.charAt(i)))
                digit = true;
            if (!Character.isLetter(newPassword.charAt(i)) && !Character.isDigit(newPassword.charAt(i)))
                nonAlphaNum = true;
        }
        return lowLetter && uppLetter && digit && nonAlphaNum;
    }
    
}
