/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.panels;

import database.ConnectionProvider;
import glbank.Account;
import java.awt.event.KeyEvent;
import java.util.List;
import java.util.Random;

/**
 *
 * @author Solanid
 */
public class PanelAccount extends javax.swing.JPanel {
    private int idc;
    private List<Account> accList= null;
    Account account = null;
    /**
     * Creates new form PanelAccount
     */
    public PanelAccount(int idc) {
        initComponents();
        this.idc=idc;
        initAccountList();
    }
    
    private void initAccountList() {
        showListOfAllAccounts();
        lblBalance.setText("");
        if (accList.isEmpty()) {
            return;
        }
        account = accList.get(0);
        lblBalance.setText(account.getBalance()+"");
    }
    
    private void showListOfAllAccounts() {
        comboListIdAcc.removeAllItems();
        accList = new ConnectionProvider().getListOfAccountsByIdc(idc);
        if (accList!=null && accList.size()>0) {
            accList.forEach((acc) -> {
                comboListIdAcc.addItem(acc.getIdacc()+" / 2701");
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboListIdAcc = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        lblBalance = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAddAmount = new javax.swing.JTextField();
        txtSubAmount = new javax.swing.JTextField();
        btnAddMoney = new javax.swing.JButton();
        btnSubstractMoney = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jSeparator1 = new javax.swing.JSeparator();
        btnNewAccount = new javax.swing.JButton();

        jLabel1.setText("Bank account:");

        comboListIdAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboListIdAccActionPerformed(evt);
            }
        });

        jLabel2.setText("Balance:");

        lblBalance.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblBalance.setText("0");

        jLabel3.setText("Cash transactions:");

        txtAddAmount.setText("0");
        txtAddAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAddAmountKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAddAmountKeyTyped(evt);
            }
        });

        txtSubAmount.setText("0");
        txtSubAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSubAmountKeyTyped(evt);
            }
        });

        btnAddMoney.setText("Add +");
        btnAddMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMoneyActionPerformed(evt);
            }
        });

        btnSubstractMoney.setText("Sub -");
        btnSubstractMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubstractMoneyActionPerformed(evt);
            }
        });

        btnNewAccount.setText("New Account");
        btnNewAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewAccountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(btnNewAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnAddMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnSubstractMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtAddAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtSubAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(15, 15, 15))
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(153, 153, 153))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboListIdAcc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBalance, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboListIdAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblBalance)
                    .addComponent(jLabel3))
                .addGap(14, 14, 14)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSubAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddMoney)
                    .addComponent(btnSubstractMoney)
                    .addComponent(btnNewAccount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboListIdAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboListIdAccActionPerformed
        // TODO add your handling code here:
        int index = comboListIdAcc.getSelectedIndex();
        if (index>=0) {
            account = accList.get(index);
            lblBalance.setText(account.getBalance()+"");
        }
    }//GEN-LAST:event_comboListIdAccActionPerformed

    private void btnAddMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMoneyActionPerformed
        String amountString = txtAddAmount.getText().trim();
        float num = Float.parseFloat(amountString);
        if (num!=0 && num>0.10) {
            new ConnectionProvider().updateAccountBalance(num, account);
        }
    }//GEN-LAST:event_btnAddMoneyActionPerformed

    private void btnSubstractMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubstractMoneyActionPerformed
        String amountString = txtSubAmount.getText().trim();
        float num = Float.parseFloat(amountString);
        num*=-1;
        if (num!=0 && num<0.10) {
            new ConnectionProvider().updateAccountBalance(num, account);
        }
    }//GEN-LAST:event_btnSubstractMoneyActionPerformed

    private void btnNewAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewAccountActionPerformed
        // TODO add your handling code here:
        if (new ConnectionProvider().addNewAccount(idc, generateRandomAccount())) {
            System.out.println("Success");
        }
        initAccountList();
    }//GEN-LAST:event_btnNewAccountActionPerformed

    private void txtAddAmountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddAmountKeyReleased
 /*        String amountString=txtAddAmount.getText().trim();
        amountString = amountString.replaceAll(" ", "");
      boolean isNumeric = postcode.chars().allMatch( Character::isDigit );
        if (!isNumeric)
            txtAddAmount.;
        float amount = Float.parseFloat(amountString);
        System.out.println(amount);*/
    }//GEN-LAST:event_txtAddAmountKeyReleased

    private void txtAddAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddAmountKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE) || c=='.')) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtAddAmountKeyTyped

    private void txtSubAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSubAmountKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE) || c=='.')) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtSubAmountKeyTyped

    private long generateRandomAccount() {
        ConnectionProvider conn = new ConnectionProvider();
        long proposalAccount = 0;
        do {
            proposalAccount = Math.abs(new Random().nextLong()%900000000)*11;
        } while (conn.isAccountAlreadyUsed(proposalAccount));
        return proposalAccount;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMoney;
    private javax.swing.JButton btnNewAccount;
    private javax.swing.JButton btnSubstractMoney;
    private javax.swing.JComboBox<String> comboListIdAcc;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JTextField txtAddAmount;
    private javax.swing.JTextField txtSubAmount;
    // End of variables declaration//GEN-END:variables
}
