/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.panels;

import database.ConnectionProvider;
import glbank.Account;
import java.awt.ComponentOrientation;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Solanid
 */
public class PanelTransactions extends javax.swing.JPanel {
    private int idc;
    private int idemp;
    private List<Account> accList = null;
    /**
     * Creates new form PanelTransactions
     */
    public PanelTransactions(int idc,int idemp) {
        this.idc = idc;
        this.idemp = idemp;
        initComponents();
        showListOfAllAccounts();
        txtAmountNonDecimalPart.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
    }

    private void showListOfAllAccounts() {
        comboListIdAcc.removeAllItems();
        accList = new ConnectionProvider().getListOfAccountsByIdc(idc);
        if (accList!=null && accList.size()>0) {
            accList.forEach((acc) -> {
                comboListIdAcc.addItem(acc.getIdacc()+" / 2701");
            });
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboListIdAcc = new javax.swing.JComboBox<>();
        txtDestAccountNumber = new javax.swing.JTextField();
        comboBoxDestBank = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtAmountNonDecimalPart = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAmountDecimalPart = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtFieldDescription = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jLabel1.setText("Source account number:");

        jLabel2.setText("Destination Account:");

        txtDestAccountNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDestAccountNumberKeyTyped(evt);
            }
        });

        comboBoxDestBank.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bank Code", "2701 (GLB)", "7500", "5600", "8360", "0900", "1100", "8410" }));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("/");

        jLabel4.setText("Amount:");

        txtAmountNonDecimalPart.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAmountNonDecimalPartKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText(",");

        txtAmountDecimalPart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountDecimalPartActionPerformed(evt);
            }
        });
        txtAmountDecimalPart.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAmountDecimalPartKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("€");

        txtFieldDescription.setColumns(20);
        txtFieldDescription.setLineWrap(true);
        txtFieldDescription.setRows(3);
        jScrollPane1.setViewportView(txtFieldDescription);

        jLabel7.setText("Description:");

        jButton2.setText("Confirm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setText("New Bank Transaction");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(181, 181, 181))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comboListIdAcc, 0, 200, Short.MAX_VALUE)
                                    .addComponent(txtDestAccountNumber))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboBoxDestBank, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtAmountNonDecimalPart, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAmountDecimalPart, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboListIdAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDestAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxDestBank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAmountNonDecimalPart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtAmountDecimalPart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtAmountDecimalPartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountDecimalPartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountDecimalPartActionPerformed

    private void txtAmountNonDecimalPartKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAmountNonDecimalPartKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }
        if (txtAmountNonDecimalPart.getText().length() >= 14 )
            evt.consume();
    }//GEN-LAST:event_txtAmountNonDecimalPartKeyTyped

    private void txtAmountDecimalPartKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAmountDecimalPartKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }
        if (txtAmountDecimalPart.getText().length() >= 2 )
            evt.consume();
    }//GEN-LAST:event_txtAmountDecimalPartKeyTyped

    private void txtDestAccountNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDestAccountNumberKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }
        if (txtDestAccountNumber.getText().length() >= 10 )
            evt.consume();
    }//GEN-LAST:event_txtDestAccountNumberKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ConnectionProvider cp = new ConnectionProvider();
        
        int srcAccIndex = comboListIdAcc.getSelectedIndex();
        long srcAcc = accList.get(srcAccIndex).getIdacc();
        float actBalance = accList.get(srcAccIndex).getBalance();
        
        String destBankString = String.valueOf(comboBoxDestBank.getSelectedItem()).trim();
        if(destBankString.isEmpty()) destBankString="0";
        boolean isNumeric = destBankString.chars().allMatch( Character::isDigit );
        int destBank;
        if(isNumeric) destBank=Integer.parseInt(destBankString); else destBank = 2701;
        
        String stringNonDecimalPart = txtAmountNonDecimalPart.getText().trim();
        if(stringNonDecimalPart.isEmpty()) 
            stringNonDecimalPart="0";
        String stringDecimalPart = txtAmountDecimalPart.getText().trim();
        if(stringDecimalPart.isEmpty()) 
            stringDecimalPart="0";
        int amountNonDecimalPart = Integer.parseInt(stringNonDecimalPart);
        float amountDecimalPart = Float.parseFloat(stringDecimalPart)/100;
        float amount = amountNonDecimalPart+amountDecimalPart;
        
        System.out.println(amount);
        
        if (srcAcc!=0 && txtDestAccountNumber.getText().trim()!="" && destBankString!="Bank Code" && amount!=0 && amount<actBalance) {
            long destAcc = Long.parseLong(txtDestAccountNumber.getText().trim());
            if (destBank==2701 && cp.isAccountAlreadyUsed(destAcc)==false) {
                System.out.println("bad idacc");
                return;
            }
            if (destAcc==srcAcc) {
                System.out.println("You cant trasfer money between same accounts!");
                return;
            }
            String desc = txtFieldDescription.getText().trim();
            try {
                if (cp.bankTransaction(amount, srcAcc, destAcc, idemp, desc, 2701, destBank)) {
                    JOptionPane.showMessageDialog(this, "Transactin successful!");
                }
                else
                    JOptionPane.showMessageDialog(this, "Transactin failed!");
            } catch (SQLException ex) {
                Logger.getLogger(PanelTransactions.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBoxDestBank;
    private javax.swing.JComboBox<String> comboListIdAcc;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAmountDecimalPart;
    private javax.swing.JTextField txtAmountNonDecimalPart;
    private javax.swing.JTextField txtDestAccountNumber;
    private javax.swing.JTextArea txtFieldDescription;
    // End of variables declaration//GEN-END:variables
}
