/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.panels;

import database.ConnectionProvider;
import glbank.Client;
import java.text.SimpleDateFormat;

/**
 *
 * @author Solanid
 */
public class PanelInfo extends javax.swing.JPanel {
    private Client client;
    
    /**
     * Creates new form jPanelInfo
     */
    public PanelInfo(Client client) {
        initComponents();
        this.client=client;
        initPanelInfo();
    }

    public void initPanelInfo() {
        lblClientId.setText(client.getIdc()+"");
        lblClientFirstName.setText(client.getFirstname());
        lblClientLastName.setText(client.getLastname());
        lblClientStreet.setText(client.getStreet());
        lblClientHouseNum.setText(client.getHousenumber()+"");
        lblClientCity.setText(client.getCity());
        lblClientPostCode.setText(client.getPostcode());
        lblClientEmail.setText(client.getEmail());
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String date = sdf.format(client.getDob());
        lblClientDob.setText(date);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblClientId = new javax.swing.JLabel();
        lblClientFirstName = new javax.swing.JLabel();
        lblClientLastName = new javax.swing.JLabel();
        lblClientStreet = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblClientHouseNum = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblClientCity = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblClientPostCode = new javax.swing.JLabel();
        lblClientDob = new javax.swing.JLabel();
        lblClientEmail = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Client ID:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("First name:");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Last name:");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Street:");

        lblClientId.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblClientId.setText("client ID");

        lblClientFirstName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblClientFirstName.setText("client firstname");

        lblClientLastName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblClientLastName.setText("client lastname");

        lblClientStreet.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblClientStreet.setText("client street");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Number:");

        lblClientHouseNum.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblClientHouseNum.setText("client housenum");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("City:");

        lblClientCity.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblClientCity.setText("client city");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("Post code:");

        lblClientPostCode.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblClientPostCode.setText("client postcode");

        lblClientDob.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblClientDob.setText("client dateofbirth");

        lblClientEmail.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblClientEmail.setText("client email");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Date of birth:");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Email:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblClientId)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblClientCity)
                            .addComponent(lblClientFirstName)
                            .addComponent(lblClientLastName)
                            .addComponent(lblClientStreet))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblClientDob)
                            .addComponent(lblClientEmail)
                            .addComponent(lblClientHouseNum)
                            .addComponent(lblClientPostCode))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblClientId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblClientFirstName)
                    .addComponent(lblClientDob)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblClientLastName)
                    .addComponent(lblClientEmail)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblClientStreet)
                    .addComponent(jLabel1)
                    .addComponent(lblClientHouseNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClientCity)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(lblClientPostCode))
                .addContainerGap(71, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblClientCity;
    private javax.swing.JLabel lblClientDob;
    private javax.swing.JLabel lblClientEmail;
    private javax.swing.JLabel lblClientFirstName;
    private javax.swing.JLabel lblClientHouseNum;
    private javax.swing.JLabel lblClientId;
    private javax.swing.JLabel lblClientLastName;
    private javax.swing.JLabel lblClientPostCode;
    private javax.swing.JLabel lblClientStreet;
    // End of variables declaration//GEN-END:variables
}
